# Generated by Django 2.2.3 on 2021-05-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favorite_genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('uuid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='movieCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='getCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(default=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movieCollections')),
                ('favorite_genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.favorite_genres')),
            ],
        ),
    ]
